<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class CheckoutRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'orderInfo.email' => 'required|email',
            'orderInfo.name' => 'required',
            'orderInfo.lastName' => 'required',
            'orderInfo.phone' => 'required',
        ];
    }
    public function messages ()
    {
        return [
            'orderInfo.email.required' => 'Неправильный емейл',
            'orderInfo.name.required' => 'Заполните поле Имя',
            'orderInfo.lastName.required' => 'Заполните поле Фамилия',
            'orderInfo.phone.required' => 'Заполните поле Телефон',
        ]; // TODO: Change the autogenerated stub
    }
}

